"""
QR token generation and validation for attendance check-in.

Security Design:
- Tokens are HMAC-SHA256 signed: gym_id + member_id → signature
- Format: base64url(gym_id|member_id|signature)
- No expiration: QR codes act as tamper-proof ID cards
- Cross-gym protection: gym_id is part of the signed payload

Why HMAC over JWT:
- QR codes need to be SHORT (scannable from phone screens)
- JWT would be ~300+ chars → hard to scan reliably
- HMAC produces ~60 char tokens → reliable QR scanning
- No expiration needed (member QR = permanent ID card)

Why not plain member IDs:
- Any member who sees another's QR could forge check-ins
- gym_id in the token prevents cross-gym misuse
- HMAC prevents anyone from generating valid tokens without the server secret

Operational Flow:
1. Admin/Staff generates QR for a member (one-time)
2. Member receives QR (printed card, WhatsApp image, or app)
3. Staff scans QR at reception desk → instant check-in
4. System validates HMAC, checks membership, prevents duplicates
"""

import base64
import hashlib
import hmac
from uuid import UUID

from app.core.config import settings

# Derive a dedicated key from JWT secret (domain separation)
_QR_KEY_PREFIX = b"gymflow-qr-v1:"


def _get_signing_key() -> bytes:
    """Derive QR signing key from the app's JWT secret."""
    return _QR_KEY_PREFIX + settings.JWT_SECRET_KEY.encode()


def _compute_signature(gym_id: UUID, member_id: UUID) -> str:
    """Compute HMAC-SHA256 signature for the gym+member pair."""
    message = f"{gym_id}|{member_id}".encode()
    sig = hmac.HMAC(_get_signing_key(), message, hashlib.sha256).digest()
    # Use first 12 bytes (96 bits) — sufficient security, shorter QR
    return base64.urlsafe_b64encode(sig[:12]).decode().rstrip("=")


def generate_qr_token(gym_id: UUID, member_id: UUID) -> str:
    """
    Generate a compact, tamper-proof QR token for a member.

    Format: base64url(gym_id|member_id|signature)
    Total length: ~80 chars — well within QR scanning limits.

    Args:
        gym_id: The gym this member belongs to
        member_id: The member's UUID

    Returns:
        Compact signed token string (suitable for QR code content)
    """
    sig = _compute_signature(gym_id, member_id)
    # Compact format: hex-encoded UUIDs (no dashes) + signature
    payload = f"{gym_id.hex}:{member_id.hex}:{sig}"
    return payload


def validate_qr_token(token: str) -> tuple[UUID, UUID] | None:
    """
    Validate a QR token and extract gym_id + member_id.

    Returns:
        (gym_id, member_id) tuple if valid, None if tampered/invalid.

    Security checks:
    1. Token format is valid (3 parts)
    2. UUIDs parse correctly
    3. HMAC signature matches (proves token was generated by our server)
    """
    try:
        parts = token.strip().split(":")
        if len(parts) != 3:
            return None

        gym_id = UUID(parts[0])
        member_id = UUID(parts[1])
        provided_sig = parts[2]

        # Recompute expected signature
        expected_sig = _compute_signature(gym_id, member_id)

        # Constant-time comparison to prevent timing attacks
        if not hmac.compare_digest(provided_sig, expected_sig):
            return None

        return (gym_id, member_id)
    except (ValueError, IndexError):
        return None
